### ISSUE TITLE
Change default vuln-scan behavior to scan all WordPress installations found in the designated path

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#126]
Currently vuln-scan only scans the first WordPress root it finds. Suggested change is to, by default, scan all WordPress installations found in a designated directory. 

Users who want to scan a single WordPress installation can designate the path to that installation accordingly or if wanting to scan multiple, but not all, WordPress installations they can use the `-w, --wordpress-path` option

**Comment by davidnuzik** [comment]
v2.1.0-rc1 (built with pip) 11/22/23

**SUMMARY:**
QA validation PASSED.
When I scan a directory now which contains more than one wordpress installation, ALL wordpress directories are scanned rather than just the first found, such as with v2.0.3. Additionally a quick check with `-w <wp_install_path>` still works as expected -- only scanning the specific install I designate.

**VALIDATION STEPS**
1. Have a directory with 2 or more WP installs (in my case took one test install and copied it twice to make 3 total)
2. Simply execute `wordfence vuln-scan <root_directory>. All paths (each of my three installs) should be scanned. They are.
3. Briefly test -w <wp_install_path> - this works as expected only scanning the one wp install path I indicate. (note the -w flag is technically not required, you can just supply it like `wordfence vuln-scan <path>` or `wordfence vuln-scan <path1> <path2>`
4. Briefly test -w by designating two of the three wp installs - both the specified installations are scanned and the 3rd is not, as expected.
5. Test scanning the root directory again, but this time with v2.0.3. It indeed only scans the first installation found.

**Comment by davidnuzik** [comment]
just after v2.1.0-rc4 at commit `1ffc8fb8` built with wheel/pip locally 12/1/23

**SUMMARY:**
QA validation PASSED.
I can confirm this latest issue found as Alex last described is resolved. Essentially, we were seeing that a path passed to `vuln-scan` or `malware-scan` would display in the tty as "{path}" instead of the actual path name like "/home/qa" for example.

**VALIDATION STEPS:**
1. Pull down the latest on `milestone/2.1.0` branch.
2. Build with wheel/pip as per install documentation. Observe wordfence is built without any errors.
3. Execute `wordfence vuln-scan .` and also with explicit paths like `/home/qa`, etc also test with malware-scan. tty now mentions proper path instead of "{path}".
