### ISSUE TITLE
Eliminate partial output when multiple columns are specified with an output format that only allows for a singular comment

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#127]
For vuln-scan: Specifying more than one column while using null-delimited or line-delimited format in stdout prints the start of the first specified column and then shows the error regarding single column. 

For malware-scan: Specifying more than one column while using null-delimited or line-delimited format in stdout proceeds with scanning files until a file is detected which then throws the error message of "Error: Only a single column can be written in this format" followed by the file in error before the scan quits. 

Suggested change is to detect from the command first both the output format along with >1 column selected and send the error before proceeding with a scan.

Example of current behavior for vuln-scan: 
<img width="1112" alt="image" src="https://github.com/wordfence/wordfence-cli/assets/104381949/807718ba-1a1d-4853-ad2b-9af1c1e0d5a9">

**Comment by davidnuzik** [comment]
`1ec10e9` (after rc2, before rc3) 11/27/23 built with pip

When you try to write output to a file such as with the following example, results may not output as expected -- notice the output for `software_type` results:

`wordfence vuln-scan --output-format null-delimited --output-path ./vuln-scan.null --output-headers ~/malware-samples/demoHackedSite/`

Unexpected output (software_type values for results)
```
software_typeSoftwareType.CORESoftwareType.CORESoftwareType.CORESoftwareType.CORESoftwareType.CORESoftwareType.CORESoftwareType.CORE
```

Similarly if you specify `line-delimited`:
```
software_type
SoftwareType.CORE
SoftwareType.CORE
SoftwareType.CORE
SoftwareType.CORE
SoftwareType.CORE
SoftwareType.CORE
SoftwareType.CORE
```

**Comment by davidnuzik** [comment]
`30e3249` (after rc2, before rc3, after merge of PR#159) 11/27/23 built with pip

**SUMMARY:**
QA validation PASSED. The problem I mentioned in my last message is resolved and I can confirm that a warning message is now shown to the user before any output.

**VALIDATION STEPS**
1. Execute a vuln-scan or malware-scan and specify `--output-format` null-delimited or line-delimited, also specify TWO OR MORE `--output-columns` (and specify an --output-path). Since these types of output only work with 1 output column, a warning is now shown to the user before proceeding with output. This warning is indeed output with the WARNING log level: `Too many output columns requested for specified format (only 1 allowed)`
2. Review the output -- it is now handled nicely and only the FIRST mentioned column is used. No errors observed while testing.
3. Smoke test this area, invoke via various args / order of args / etc. No issues observed.
4. Test the issue I reported in my prior message regarding output values for "software_type" column - they now show as expected like `core` instead of `SoftwareType.CORE` regardless if with null-delimited or line-delimited output format.


**NOTES:**
You can tell the warning is indeed "WARNING" log level by passing `--prefix-log-levels`
