### ISSUE TITLE
Dependency restriction on pyproject.toml using tilde

### ISSUE THREAD

**Issue by pesc** [wordfence/wordfence-cli#157]
In the `pyproject.toml` file, the `build-system` section sets the `requires` using the tilde requirement to Major.Minor.Patch
[requires = [ "setuptools~=68.0.0" ]](https://github.com/wordfence/wordfence-cli/blob/5aada8e2e32136b14d80a9f0bdbba218e1f299df/pyproject.toml#L3)

This only allows the setuptools to change it's patch-version:
* 68.0.1 ✅ 
* 68.2.2 🚫 
* 69.0.2 🚫 

Is this the intended behavior, or could it be changed to use: 
```
[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
```

This would allow newer version (minor, major)

**Comment by akenion** [comment]
I will adjust this in the next release to allow later minor versions as well. We intentionally do not allow later major versions as they may break backwards compatibility and require additional evaluation/testing to ensure compatibility with the project.

**Comment by davidnuzik** [comment]
milestone/2.1.0 12/8/23

**SUMMARY:**
QA validation PASSED.
I can confirm the changes in https://github.com/wordfence/wordfence-cli/pull/158/files as the requirements.txt and pyproject.toml files have been updated to allow later minor versions (i.e. the extra .0 for patch version not set now). Upon building the wheel with python, I can see that setuptools~=68.0 is now mentioned (as per the change which now allows any patch of 68.0)

**VALIDATION STEPS**
1. Inspect requirements.txt and pyproject.toml. They have the changes from #158 and look good.
2. Try to build the wheel with python, during the build process I see `* Installing packages in isolated environment... (setuptools~=68.0)` (i.e. the change works as expected, build process is requiring `setuptools~=68.0.x` now instead of `setuptools~=68.0.0`)
