### ISSUE TITLE
Terms acceptance prompt displays "Wordfence CLI Free" for paid licenses when cache entry is absent

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#160]
The license type is not currently stored, so an API call will need to be made in this case to determine the license type in order to display the correct prompt.

**Comment by davidnuzik** [comment]
v2.1.0rc4 12/1/23

**SUMMARY:**
QA validation PASSED. I executed various checks around terms acceptance including but not limited to:
- Upgrade from older Wordfence CLI 2.x to v2.1.0rc4 (where cache was used at least once with older wordfence CLI 2.x to malware-scan and vuln-scan) ensure that terms acceptance is still recorded when try to scan with v2.1.0rc4 (i.e. I am not prompted yet again to accept TOS since I already did prior with v2.0.3 in my case).
- Have a free license, upgrade to a paid/premium license, execute scans with --no-cache and also try again but with --purge-cache (shouldn't matter but tested each regardless) --> Ensure terms acceptance doesn't mention "Wordfence CLI Free" since now we have a paid/premium license.
- Various other tests around terms acceptance, configuration, passing -l <license>, etc smoke tested as I covered these quite recently with regression testing on RC4. Also smoke tested with arm64 architecture.

**VALIDATION STEPS (DETAILS):**

1. On a fully clean system (brand new ec2 instance), run a malware-scan and vuln-scan with Wordfence CLI v2.0.3 (current release as of the time I am testing). The configure process requires accepting terms and I did this. Now, run with the v2.1.0rc4 binary instead -- a malware-scan or vuln-scan -- I can confirm with the same cache, I am not prompted to accept terms and the scans work as expected.
2. On a "clean system" (wf dirs deleted) test step 1 again. No issues.
3. On a non-clean system (i.e. I already had wordfence running on this environment prior and I am just running vuln-scan and malware-scan again but with rc4) test step 1 again. No issues.
4. Now, test an environment which currently has a free license, upgrade the license to premium by manually placing the premium key in the config ini file. Run a malware-scan. Ensure there is not TOS prompt or other issues; no issues observed.
5. Test again, with a "clean system" (wf dirs deleted), after TOS acceptance with free license, run a malware-scan again but with -l <premium key> supplied on the command line -- same result, works as expected I am not prompted to accept TOS again.
6. Last, smoke test in a couple of other environments. Some of which have had older wordfence CLI installed. I didn't observe any unexpected issues while testing. I was not re-prompted for terms acceptance when I had already configured/accepted in the environment prior. The change in PR 164 seems to work as expected - the old terms acceptance in my cache gets converted to the new format (from what I can tell as I don't get re-prompted) and when I upgrade to a premium key I am not prompted to accept again.

**Comment by ewodrich** [comment]
Case 3279 has been added to wordfence-www cases to insert a record in the appropriate db table upon paid license checkout so that the already accepted terms can be validated for CLI for the applicable license the first time it is invoked, such as when configuring a new install.

**Comment by ewodrich** [comment]
The main thing to look out for in the retest is that new premium CLI licenses should not trigger accepting terms since the terms are accepted upon purchase. Verifying alongside https://github.com/wordfence/wordfence-central-api/issues/2529. Tested the following items to ensure that new or existing PAID licenses no longer prompt for terms acceptances and auto-generated free keys are still prompting for terms acceptance as they should.

- `wordfence configure` installs new free key and prompts for terms
- `wordfence vuln-scan / malware-scan . -l [new cli key]` does not prompt for terms
- `wordfence vuln-scan / malware-scan . -l [new cli key] --no-cache` does not prompt for terms
- `wordfence vuln-scan / malware-scan . -c /Users/Esthe/.config/wordfence/wordfence-prem.ini --no-cache` does not prompt for terms
