### ISSUE TITLE
Running malware-scan on a nonexistant path triggers an error, but does not complete or terminate

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#168]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/alex/Defiant/wordfence-cli/wordfence/scanning/scanner.py", line 279, in run
    locator.locate()
  File "/home/alex/Defiant/wordfence-cli/wordfence/scanning/scanner.py", line 216, in locate
    if not self._is_loop(self.path):
  File "/home/alex/Defiant/wordfence-cli/wordfence/scanning/scanner.py", line 143, in _is_loop
    if os.path.samefile(path, realpath):
  File "/usr/lib/python3.8/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/does-not-exist'
```

**Comment by ewodrich** [comment]
Verified I can input an invalid path for -c/--configure option and instead of getting a traceback error I get a more expected error of "Error: Failed to create directory at </path>" on Mac & Linux. Also confirmed -c pointing to a valid path with .ini file works as expected. 

Further testing, as root on Linux allowed me to input a non-existent path. I was first prompted with "No existing config file found at /Users/Esthe/.config/wordfence/wordfence-test.ini" and then was prompted through the regular `configure` flow.  The flow completed without error.

**Comment by ewodrich** [comment]
Verified the following on both Mac and Linux: 

- Valid path runs command as intended 
- Valid path with non-existent config file triggers & completes configure
  - No, closes without error
  - Yes, completes config
- Invalid path triggers configure and then fails with error when creating directory
- Valid path without config file designated sends appropriate error message
- Running as root creates the directories specified in the path if they don't already exist (linux)
- Free license installs as expected without cache issues
