### ISSUE TITLE
Improve symlink handling for vuln-scan 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#193]
Recursive symlinks are causing a variety of scan duplications or even errors depending on how/where the symlinks are pointing. 

Add recursive symlink detection to the vuln-scan command like we have for malware-scan. 

Example error on symlink detection: Error: Unable to scan directory at ./wp-content/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir/same-dir

**Comment by davidnuzik** [comment]
v2.1.0rc8 12/11/23

The change in #194 works -- but I also noticed that when I have symlinks that are not recursive / i.e. not pointing to themselves the symlinks are not followed. This is unlike `malware-scan` which does follow links and can scan other wordpress installs / paths. I would expect the same behavior with vuln-scan. That said I don't know if we should block release any further -- this isn't that big of a deal in my opinion. Perhaps we could consider fixing this / changing the behavior in our next release? I could file a separate issue for this if we'd like.

@akenion could I get your input/opinion?

**Comment by akenion** [comment]
@davidnuzik Symlinks that are not recursive should be followed. We should go ahead and correct this for the 2.1.0 release. I'll re-open the issue and take a look.

**Comment by akenion** [comment]
After discussing further with @davidnuzik, the behavior mentioned above was actually related to the effective nesting of multiple WordPress installations (via symlink) and is intended behavior. No additional changes are needed at this point.

**Comment by davidnuzik** [comment]
v2.1.0rc8 12/12/23

**SUMMARY:**
QA validation PASSED.

Initially there was some confusion on my end around symlinks and vuln-scan following them. You can see our prior comments in this case. Basically, I misunderstood the behavior of vuln-scan compared to malware-scan when handling symlinks that are within a wordpress install. Vuln-scan and malware-scan are completely different tools and malware-scan will handle symlinks differently. It will follow them including if they are in a wordpress install location pointing to another wordpress install location on disk (or other locations). Malware-scan is for scanning malware at any path including symlinks you may have in that path or lower. Vuln-scan does not -- specifically if the link is in a wordpress install and pointing to another wordpress install and this is by design and expected.

When using vuln-scan you should typically supply a specific path or paths. However, you can designate a parent folder (such as `/var/www` where you may have 1 _or more_ wordpress installs - it will scan all wordpress installs it finds on disk at that location. It will _also_ follow symlinks at `/var/www` but if you have symlinks WITHIN a wordpress install pointing to another wordpress install -- those symlinks will not be "followed" and scanned. This is expected behavior.

While I expect it unlikely folks have a symlink in any one wordpress install pointing to another wordpress install (and wish to tell wordfence cli to scan one and expect it to also scan the other that is symlinked) -- if you have such a particular setup it is better to designate explicitly the wordpress installs you wish to scan.

**VALIDATION STEPS**
1. Have a wordpress install with symlinks -- I have several to test that vuln-scan does NOT follow them such as ones that are nested/pointing to themselves essentially OR other wordpress installs. For example I have one that is just linked to `.` in the wordpress install (itself / its own path), one that points a few dirs up, and one that points to another wordpress install.
2. Either at the wordpress install working dir or outside of it, run a vuln-scan and designate the correct path pointing to my wordpress install with all those symlinks within it. For example in the working dir simply `wordpress vuln-scan .` outside of it specify the dir `wordpress vuln-scan ~/demosite` -- test both.
3. Observe the vuln-scan output -- indeed only one site is detected and the designated path is scanned. The symlinks are not followed. Prior to the fix it would keep following nested symlinks forever (until errors out). The change fixes this issue.

**NOTES:**
