### ISSUE TITLE
Scanning directory containing sibling symlinks results in files being scanned multiple times

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#207]
A directory structure with symlinks that point to sibling directories will result in the same paths being scanned multiple times

Example structure:
- parent-dir
  - some-site/
    - some-file
  - some-site-link -> some-site

`wordfence malware-scan parent-dir` will scan `some-file` twice in the above example.

(Reported by @ewodrich)

**Comment by akenion** [comment]
The solution to this involves tracking paths that have already been scanned in memory. This could potentially have a negative impact on scan performance and memory usage when scanning larger filesystems, but is implemented in a way that should be efficient, so I don't anticipate this being a problem. We should run some tests to confirm that performance is comparable to prior releases in this scenario.

**Comment by davidnuzik** [comment]
v3.0.1rc5

**SUMMARY:**
QA validation PASSED. I can confirm the issue is resolved. I set up a directory structure like the example shown in the issue description. Upon running a malware-scan a file is not scanned twice, further I see "Skipping already queued path: {path}" further indicating the [change](https://github.com/wordfence/wordfence-cli/pull/208/files#diff-032691d818eadea3bd65f6ff2d9e1628d1b828c013ea0d958dcbf6f5ddeac738R199) works as it skipped re-scanning a dir it ran across while following a symlink.

**VALIDATION STEPS**
1. Create a directory structure just like is shown in the github issue body. The directory containing the root folder for a wordpress install now also has a simlink pointing to that folder in the same dir, as a sibling.
2. Run `wordfence malware-scan parent-dir` and observe the results and messages about "Skipping already queued path". The scans are not repeated now.
3. Test again but with RC3 and successfully reproduced the reported issue (this ensures I understand the issue and correctly can reproduce to prove my testing done is correct).

**NOTES:**
_I will leave this issue open for now. Once a new RC / final RC is out prior to release I will smoke test this again to ensure all is still well then mark the issue as qa-passed_

**Comment by davidnuzik** [comment]
Smoke tested - same directory setup again with rc7 - no issues; marking this issue as qa-passed now; this is most likely our last RC.
