### ISSUE TITLE
Input from stdin isn't processed until an entire chunk is available

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#231]
Input passed via stdin (such as files to scan for `malware-scan`) is only read in whole chunks of 1024 and less is only accepted when end-of-file is reached. This makes reading partial input from a still-running process (such as a pipe from another process, like `inotifywait`) problematic (it will never be processed if the chunk size isn't met and the process doesn't exit).

**Comment by davidnuzik** [comment]
v3.0.2rc3

**SUMMARY:**
QA validation PASSED. I successfully reproduced the issue and was able to validate the fix using the same process.

**REPRODUCTION STEPS:**
1. Using v3.0.1, execute the following: `inotifywait -m -r -q -e close_write --format '%w%f' . | wordfence malware-scan -s $'\n'`
2. The issue is reproduced. The input is not handled as expected -- I see no action taking place. This is due to the way stdin was handled prior -- as described in the issue.

**VALIDATION STEPS:**
1. Execute the same as outlined above in the reproduction steps, but with v3.0.2rc3. 
2. The issue is validated. The input is now _correctly_ handled as expected -- If I alter just one file in the current directory malware-scan will scan the file.

**NOTES:**
Files will not be re-scanned during runtime. This is currently an expected behavior based on how the CLI is designed. We may consider an option to permit re-scanning of "duplicates" here in the future, but this is to be determined.
