### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by zydrunast** [wordfence/wordfence-cli#68]
I have Debian 10.13

wordfence is not working with python 3.8 (all soft is installed with apt from Debian 10 releases, no custom compilations.

[11580] Error loading Python lib '/tmp/_MEIDjZOhM/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIDjZOhM/libpython3.8.so.1.0)

**Comment by akenion** [comment]
The pre-compiled version of Wordfence CLI is built against a specific version of GNU libc which differs from what's available on Debian 10. We are working on improving our build process to provide pre-compiled binaries to accommodate different platforms and library versions, but this is not yet available. In the meantime, you should be able to install Wordfence CLI via one of our alternate installation methods.

The simplest method is to install from `pypi.org` via `pip`. Assuming `pip` (I believe it will be `pip3` on Debian) and Python 3.8 are already installed, you should be able to just run:
```
pip3 install wordfence
```

Alternatively, you can use the `.whl` file distributed with the repo to install via `pip`:
https://github.com/wordfence/wordfence-cli/blob/main/docs/Installation.md#pip-installation-of-the-wheel-archive-file

If using `pip` is problematic or you encounter issues with that method, manually installing Wordfence CLI is also an option:
https://github.com/wordfence/wordfence-cli/blob/main/docs/Installation.md#manual-installation

**Comment by davidnuzik** [comment]
This should be all good to go now -- I do not see the GLIBC errors on my Ubuntu 16.04 and 18.04 test VMs now. That said I have not tried to manually install (or set up a repo) for Python 3.8 or better (since it is not provided by the repos in these versions).

What I'll do now is try to get that set up so I can confirm that when Python 3.8 (and any required pip packages) are setup it should work now.

**Comment by davidnuzik** [comment]
I tried setting up Debian Buster (10.13, i.e. the latest) but it only provides Python 3.7.3, not 3.8 or better. Perhaps you have other repos set up @zydrunast ?
I'll try to set it up with another repo or other means but unless I'm mistaken Debian 10.13 does not include Python 3.8 out of the box with default repos.

**Comment by davidnuzik** [comment]
v2.0.1-rc6 10/31/2023

**SUMMARY:**
QA validation PASSED.
Both Debian Buster (10.13) and Ubuntu 18.04 work out of the box for me as long as I use the binary. If using the pip installation method it's necessary to set up Python 3.8. I personally would recommend the binary for older operating systems such as Buster and 18.04. Whereas Ubuntu 20.04 and newer for example should work fine with pip install methods (i.e. no extra steps required to get Python 3.8 installed, etc)

**VALIDATION STEPS**
1. Deploy binary to Debian 10.13 VM, smoke test
2. Deploy binary to Ubuntu 18.04 VM, smoke test

**NOTES:**
Note, plenty of other testing has been done before on Ubuntu environments with 20.04 and newer VMs. 18.04 only smoke test, Debian 10.13 only smoke test. That said since the binary runs and smoke test looks good I'm pretty confident 18.04 and Debian 10 should be golden as well.
