### ISSUE TITLE
Build deb package

### ISSUE THREAD

**Issue by briandefiant** [wordfence/wordfence-cli#90]

**Comment by davidnuzik** [comment]
I have been playing with the .deb package lately and not observed any serious or not-yet-known issues using various environments such as newer Ubuntu. When a new .deb package is available (such as a possible rc5 we might release) I can briefly test again in various environments and ensure it installs and gets removed as expected. Else, if we do not release an RC5 prior to 2.0.1 release I can use what I have but expect to label the case as `qa-passed` from all my testing thus far.

**Comment by davidnuzik** [comment]
v2.0.1-rc5 10/30/2023

**SUMMARY:**
QA validation PASSED.
I have been testing the .DEB package prior primarily with rc4. I largely smoke tested with rc5 now, due to all my testing already done prior and primarily to ensure nothing really changed / broke with some build changes made. I didn't encounter any issues and was successful in installing the .deb package with Ubuntu 20.04 as well as in removing it -- I used apt so all dependencies would be obtained. As known currently, Ubuntu 18.04 and older does not work by default. This is because Python 3.8 or better is not provided in the Ubuntu repos for these versions. Python 3.8 is currently supported, if it can be properly installed in such environments, the binary should work, but the deb package may not since the actual python package(s) need to provide 3.8 or better.

**VALIDATION STEPS**
Smoke test with Ubuntu 20.04:
1. Install via apt `sudo apt install -f ./wordfence.deb`. Dependencies are obtained and the install succeeds without errors.
2. Smoke test `wordfence` -- it behaves as expected just like the binary.
3. Remove via apt `sudo apt remove wordfence`. wordfence package is removed, apt notes that one or more python packages are not longer needed and can optionally be removed with `apt autoremove`. Removal of the wordfence package works successfully. As expected, the ~/.cache/wordfence and ~/.config/wordfence directories and files remain.
