### ISSUE TITLE
Improve signing and checksumming of release assets

### ISSUE THREAD

**Issue by briandefiant** [wordfence/wordfence-cli#98]
We currently generate too many signatures (one for each package type and one for each checksum file). We should generate a single checksum file for all release assets and sign that file instead. Documentation should also be updated to reflect this.

**Comment by davidnuzik** [comment]
v2.0.1-rc5 10/30/2023

**SUMMARY:**
QA validation PASSED.
Single checksum file now, and docs change looks good!

**VALIDATION STEPS**
1. Refer to [docs/Installation.md](https://github.com/wordfence/wordfence-cli/blob/milestone/voodoo-child/docs/Installation.md#verifying-the-authenticity-of-a-release-asset) (note that this links to voodoo-child branch since we haven't merged to mainline yet) and follow the "Verifying the Authenticity of a Release Asset" section.
2. Per the documentation, obtain the public GPG key and import it. (Optionally sign it with your private key).
3. Download the `checksums.txt` release asset (rc5) and `checksums.txt.asc`. Verify `checksums.txt` using `checksums.txt.asc`
4. When verify, ensure get output that is similar to the example in the Installation.md doc.
5. Download each asset, verify each via `sha256sum` e.g. within the directory containing all assets including checksums files, run `sha256sum --ignore-missing -c checksums.txt` and get an "OK" for each.

```
sha256sum --ignore-missing -c checksums.txt
wordfence_amd64.tar.gz: OK
wordfence_arm64.tar.gz: OK
wordfence.deb: OK
wordfence-2.0.1rc5-py3-none-any.whl: OK
wordfence-2.0.1rc5.tar.gz: OK
```

**NOTES:**
**_BEFORE_** the change (RC4 pictured)
![image](https://github.com/wordfence/wordfence-cli/assets/45179589/c93ed28a-7887-4355-9782-231fea8924e1)

**AFTER** the change (RC5 pictured)
![image](https://github.com/wordfence/wordfence-cli/assets/45179589/41c9d54a-5e20-47c6-bd1c-d89f956c93eb)
